# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]
incremental: true
future: true # allow posts with future dates

sass:
  sass_dir: assets/css
  style: :compressed

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "BitDevsGoma"
description: "BitDevsGoma est un meetup (rencontre) consacré à la recherche et au développement de Bitcoin."

# Leave out some files
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.sass-cache']

