title: 'BitDevsGoma'
tagline: 'BitDevsGoma is a monthly meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'Events', url: '/events'}
  - {name: 'Luma', url: 'https://lu.ma/user/BitdevsGoma', external: true}
  - {name: 'Whatsapp', url: 'https://chat.whatsapp.com/LDcuoctOUBE5dp9eYnjx1V', external: true}
  - {name: 'Tweeter', url: 'https://x.com/bitdevsGoma', external: true}
